### ISSUE TITLE
Problems building on Mac OS

### ISSUE THREAD

**Issue by LucasMW** [foxnne/aftersun#16]
Had problems building on Mac OS:

`zig build run`

> Fetch Packages [1/1] mach... /Users/redacted/Cloned_From_Github/aftersun/build.zig.zon:14:21: error: hash mismatch: expected: 1220a1ac8dba2fee590af6bafce6e1d5a768b93456e8877fe3d5402f19aec3d5d696, found: 122097ee957fdc50c8f8a18a7353f1e75316ef1614cc28445507015d9421d1230f19
>             .hash = "1220a1ac8dba

`zig version`

> 0.11.0

**Comment by LucasMW** [comment]
Ops, forget about it. Just read it needs a newer version

**Comment by foxnne** [comment]
Glad you were able to get it running!
