### ISSUE TITLE
Incorrect condition in component registration loop

### ISSUE THREAD

**Issue by Luexa** [foxnne/aftersun#6]
The [`register`] function iterates over the declarations of a container type `T` and adds each `Type` found within `T` as a component. However, the loop responsible for this apparently checks `@TypeOf(T) == type` when the intention is probably `@TypeOf(Type) == type`.

Additionally, currently only struct containers are supported. While this is probably fine for the most part, it could be useful to support other types of containers like `union`. This is easily achievable through `std.meta.declarations`.

Suggested changes:

```diff
 /// Registers all public declarations within the passed type
 /// as components.
 fn register(world: *flecs.EcsWorld, comptime T: type) void {
-    const decls = @typeInfo(T).Struct.decls;
+    const decls = comptime std.meta.declarations(T);
     inline for (decls) |decl| {
         if (decl.is_pub) {
             const Type = @field(T, decl.name);
-            if (@TypeOf(T) == type) {
+            if (@TypeOf(Type) == type) {
                 flecs.ecs_component(world, Type);
             }
         }
     }
}
```

[`register`]: https://github.com/foxnne/aftersun/blob/8062c05c21847a991582945ab4b6d4a14c9e8093/src/aftersun.zig#L95-L107

**Comment by foxnne** [comment]
Thanks for the issue! I'm about to commit your changes. Appreciate it!

**Comment by Luexa** [comment]
> Thanks for the issue! I'm about to commit your changes. Appreciate it!

No problem! Although I haven't made much progress in doing so, I'll probably use Aftersun as reference for some of my own code, so it's only fair for me to suggest improvements that I may think of while browsing the codebase.
